// Generated by CoffeeScript 1.3.3
(function() {
  var Conway, Graphics,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Graphics = (function() {

    function Graphics() {}

    Graphics.prototype.STROKE = "#000";

    Graphics.prototype.FILL = "#DDD";

    Graphics.prototype.drawSquare = function(x, y, w, h, s, f) {
      if (s == null) {
        s = this.STROKE;
      }
      if (f == null) {
        f = this.FILL;
      }
      this.ctx.beginPath();
      this.ctx.rect(x, y, w, h);
      this.ctx.fillStyle = f;
      this.ctx.fill();
      this.ctx.lineWidth = 1;
      this.ctx.strokeStyle = s;
      return this.ctx.stroke();
    };

    Graphics.prototype.drawLine = function(x, y, x2, y2, s) {
      if (s == null) {
        s = this.GRID_STROKE;
      }
      this.ctx.strokeStyle = s;
      this.ctx.beginPath();
      this.ctx.moveTo(x, y);
      this.ctx.lineTo(x2, y2);
      this.ctx.closePath();
      return this.ctx.stroke();
    };

    return Graphics;

  })();

  Conway = (function(_super) {

    __extends(Conway, _super);

    function Conway() {
      return Conway.__super__.constructor.apply(this, arguments);
    }

    Conway.prototype.GRID_STROKE = "lightgrey";

    Conway.prototype.DUDE = "green";

    Conway.prototype.COL_W = 10;

    Conway.prototype.ROW_H = 10;

    Conway.prototype.FPS = 25;

    Conway.prototype.initialize = function() {
      var _this = this;
      this.canvas = document.getElementById("myCanvas");
      this.ctx = this.canvas.getContext("2d");
      this.width = this.ctx.canvas.width;
      this.height = this.ctx.canvas.height;
      this.initBoard();
      this.initGrid();
      this.bindEvents();
      this.initStats();
      return setInterval((function() {
        if (!_this.mouse_state) {
          _this.stats.begin();
          _this.render();
          return _this.stats.end();
        }
      }), 1000 / this.FPS);
    };

    Conway.prototype.initStats = function() {
      this.stats = new Stats;
      this.stats.domElement.style.position = 'absolute';
      this.stats.domElement.style.right = '8px';
      this.stats.domElement.style.top = '8px';
      return document.body.appendChild(this.stats.domElement);
    };

    Conway.prototype.render = function() {
      this.clearCanvas();
      this.drawBoard();
      this.drawGridData();
      return this.tick();
    };

    Conway.prototype.tick = function() {
      var cell, col, cols, is_alive, kill, num_neighbours, resurect, row, value, _i, _j, _k, _l, _len, _len1, _len2, _len3, _ref, _results;
      kill = [];
      resurect = [];
      _ref = this.grid;
      for (col = _i = 0, _len = _ref.length; _i < _len; col = ++_i) {
        cols = _ref[col];
        for (row = _j = 0, _len1 = cols.length; _j < _len1; row = ++_j) {
          value = cols[row];
          num_neighbours = this.numNeighbors(col, row);
          is_alive = value ? true : false;
          if (is_alive && num_neighbours < 2) {
            kill.push([col, row]);
          }
          if (is_alive && num_neighbours > 3) {
            kill.push([col, row]);
          }
          if (!is_alive && num_neighbours === 3) {
            resurect.push([col, row]);
          }
        }
      }
      for (_k = 0, _len2 = kill.length; _k < _len2; _k++) {
        cell = kill[_k];
        this.grid[cell[0]][cell[1]] = 0;
      }
      _results = [];
      for (_l = 0, _len3 = resurect.length; _l < _len3; _l++) {
        cell = resurect[_l];
        _results.push(this.grid[cell[0]][cell[1]] = 1);
      }
      return _results;
    };

    Conway.prototype.bindEvents = function() {
      var _this = this;
      this.canvas.onmousedown = function(e) {
        return _this.onMouseDown(e);
      };
      this.canvas.onmouseup = function(e) {
        return _this.onMouseUp(e);
      };
      this.canvas.onmouseout = function(e) {
        return _this.onMouseUp(e);
      };
      return this.canvas.onmousemove = function(e) {
        return _this.onMouseMove(e);
      };
    };

    Conway.prototype.onMouseDown = function(e) {
      this.mouse_state = 1;
      return this.set(this.getPos(e));
    };

    Conway.prototype.onMouseUp = function(e) {
      return this.mouse_state = 0;
    };

    Conway.prototype.onMouseMove = function(e) {
      if (this.mouse_state) {
        return this.set(this.getPos(e));
      }
    };

    Conway.prototype.set = function(_arg) {
      var col, row;
      col = _arg[0], row = _arg[1];
      this.drawGridItem(col, row);
      return this.grid[col][row] = 1;
    };

    Conway.prototype.getPos = function(e) {
      var col, position, row, x, y;
      position = this.canvas.getBoundingClientRect();
      x = e.clientX - position.left;
      y = e.clientY - position.top;
      col = Math.floor(x / this.COL_W);
      row = Math.floor(y / this.ROW_H);
      return [col, row];
    };

    Conway.prototype.numNeighbors = function(col, row) {
      var down, down_left, down_right, left, right, up, up_left, up_right;
      up = this.getGridItem(col, row - 1);
      down = this.getGridItem(col, row + 1);
      left = this.getGridItem(col - 1, row);
      right = this.getGridItem(col + 1, row);
      up_right = this.getGridItem(col + 1, row - 1);
      down_right = this.getGridItem(col + 1, row + 1);
      down_left = this.getGridItem(col - 1, row + 1);
      up_left = this.getGridItem(col - 1, row - 1);
      return up + down + left + right + up_right + down_right + down_left + up_left;
    };

    Conway.prototype.getGridItem = function(col, row) {
      if (col < 0 || row < 0 || col >= this.num_cols || row >= this.num_rows) {
        return 0;
      }
      return this.grid[col][row];
    };

    Conway.prototype.initBoard = function() {
      this.max_width = this.width - (this.width % this.COL_W);
      this.max_height = this.height - (this.height % this.ROW_H);
      this.num_cols = this.max_width / this.COL_W;
      return this.num_rows = this.max_height / this.ROW_H;
    };

    Conway.prototype.initGrid = function() {
      var x, y, _i, _ref, _results;
      this.grid = [];
      _results = [];
      for (x = _i = 0, _ref = this.num_cols; 0 <= _ref ? _i < _ref : _i > _ref; x = 0 <= _ref ? ++_i : --_i) {
        this.grid[x] = [];
        _results.push((function() {
          var _j, _ref1, _results1;
          _results1 = [];
          for (y = _j = 0, _ref1 = this.num_rows; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; y = 0 <= _ref1 ? ++_j : --_j) {
            _results1.push(this.grid[x][y] = Math.round(Math.random()));
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    Conway.prototype.clearCanvas = function() {
      return this.ctx.clearRect(0, 0, this.width, this.height);
    };

    Conway.prototype.drawBoard = function() {
      this.drawSquare(0, 0, this.max_width, this.max_height);
      return this.drawGrid();
    };

    Conway.prototype.drawGrid = function() {
      var x, y, _i, _j, _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _results;
      for (x = _i = _ref = this.COL_W, _ref1 = this.max_width, _ref2 = this.COL_W; _ref <= _ref1 ? _i < _ref1 : _i > _ref1; x = _i += _ref2) {
        this.drawLine(x, 1, x, this.max_height - 1);
      }
      _results = [];
      for (y = _j = _ref3 = this.ROW_H, _ref4 = this.max_height, _ref5 = this.ROW_H; _ref3 <= _ref4 ? _j < _ref4 : _j > _ref4; y = _j += _ref5) {
        _results.push(this.drawLine(1, y, this.max_width - 1, y));
      }
      return _results;
    };

    Conway.prototype.drawGridData = function() {
      var col, cols, row, value, _i, _len, _ref, _results;
      _ref = this.grid;
      _results = [];
      for (col = _i = 0, _len = _ref.length; _i < _len; col = ++_i) {
        cols = _ref[col];
        _results.push((function() {
          var _j, _len1, _results1;
          _results1 = [];
          for (row = _j = 0, _len1 = cols.length; _j < _len1; row = ++_j) {
            value = cols[row];
            if (value === 1) {
              _results1.push(this.drawGridItem(col, row));
            } else {
              _results1.push(void 0);
            }
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    Conway.prototype.drawGridItem = function(col, row, f) {
      if (f == null) {
        f = this.DUDE;
      }
      return this.drawSquare(col * this.COL_W, row * this.ROW_H, this.COL_W, this.ROW_H, "", f);
    };

    return Conway;

  })(Graphics);

  window.onload = function() {
    var conway;
    conway = new Conway;
    return conway.initialize();
  };

}).call(this);
