// Generated by CoffeeScript 1.3.3
(function() {

  window.Graphics = (function() {

    function Graphics() {}

    Graphics.prototype.STROKE = "#000";

    Graphics.prototype.FILL = "#DDD";

    Graphics.prototype.drawSquare = function(x, y, w, h, s, f) {
      if (s == null) {
        s = this.STROKE;
      }
      if (f == null) {
        f = this.FILL;
      }
      this.ctx.beginPath();
      this.ctx.rect(x, y, w, h);
      this.ctx.fillStyle = f;
      this.ctx.fill();
      this.ctx.lineWidth = 1;
      this.ctx.strokeStyle = s;
      return this.ctx.stroke();
    };

    Graphics.prototype.drawLine = function(x, y, x2, y2, s) {
      if (s == null) {
        s = this.GRID_STROKE;
      }
      this.ctx.strokeStyle = s;
      this.ctx.beginPath();
      this.ctx.moveTo(x, y);
      this.ctx.lineTo(x2, y2);
      this.ctx.closePath();
      return this.ctx.stroke();
    };

    return Graphics;

  })();

}).call(this);
